FROM golang:1.25 AS source

ARG VERSION=v0.68.0
ARG REPO=https://github.com/fatedier/frp.git

WORKDIR /src

RUN apt-get update && \
apt-get install -y --no-install-recommends git ca-certificates && \
git clone --depth=1 --branch "${VERSION}" "${REPO}" frp && \
rm -rf /var/lib/apt/lists/*

FROM node:22 AS web-builder

COPY --from=source /src/frp/web/package.json /web/package.json
COPY --from=source /src/frp/web/shared/ /web/shared/
COPY --from=source /src/frp/web/frpc/ /web/frpc/
WORKDIR /web
RUN npm install
WORKDIR /web/frpc
RUN npm run build

FROM golang:1.25 AS building

WORKDIR /building
COPY --from=source /src/frp/ ./
COPY --from=web-builder /web/frpc/dist /building/web/frpc/dist

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frpc -o bin/frpc ./cmd/frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
