FROM golang:1.25 AS source

ARG VERSION=v0.68.0
ARG REPO=https://github.com/fatedier/frp.git

WORKDIR /src

RUN apt-get update && \
apt-get install -y --no-install-recommends git ca-certificates && \
git clone --depth=1 --branch "${VERSION}" "${REPO}" frp && \
rm -rf /var/lib/apt/lists/*

FROM node:22 AS web-builder

WORKDIR /web/frps
COPY --from=source /src/frp/web/frps/ ./
RUN npm install
RUN npm run build

FROM golang:1.25 AS building

WORKDIR /building
COPY --from=source /src/frp/ ./
COPY --from=web-builder /web/frps/dist /building/web/frps/dist

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frps -o bin/frps ./cmd/frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
