# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Upload To Aliyun Registry
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "namespace"
        required: true
        default: "dup4"
      components:
        description: "components"
        required: true
      tag:
        description: "tag"
        required: true
      target_registry:
        description: "registry"
        required: true
        default: "registry.cn-shanghai.aliyuncs.com"
      target_namespace:
        description: "target_namespace"
        required: true
        default: "dup4"

jobs:
  upload_to_aliyun_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ALiYun Shanghai Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_TOKEN }}

      - name: Set Name
        id: set_name
        run: |
          if [ ${{ github.event.inputs.namespace }} != "_" ]; then
              echo "::set-output name=components::${{ github.event.inputs.components }}"
          else
              echo "::set-output name=components::${{ github.event.inputs.namespace }}/${{ github.event.inputs.components }}"
          fi
          echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          echo "::set-output name=target_registry::${{ github.event.inputs.target_registry }}"
          echo "::set-output name=target_namespace::${{ github.event.inputs.target_namespace }}"

      - name: Pull and Push
        env:
          name: ${{ steps.set_name.outputs.name }}
          tag: ${{ steps.set_name.outputs.tag }}
        run: |
          docker pull ${{ env.name}} :${{ env.tag }}
          docker tag ${{ env.name }}:${{ env.tag }} ${{ github.event.inputs.target_registry }}/${{ github.event.inputs.target_namespace }}/${{ github.event.inputs.components }}:${{ env.tag }}
          docker push ${{ github.event.inputs.target_registry }}/${{ github.event.inputs.target_namespace }}/${{ github.event.inputs.components }}:${{ env.tag }}
