# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Upload To Aliyun Registry
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "namespace"
        required: true
        default: "dup4"
      registry:
        description: "registry"
        required: true
        default: "registry.cn-shanghai.aliyuncs.com"
      components:
        description: "components"
        required: true
      tag:
        description: "tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ALiYun Shanghai Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_TOKEN }}

      - name: Pull and Push
        run: |
          docker pull ${{ github.event.inputs.namespace }}/${{ github.event.inputs.components }}:${{ github.event.inputs.tag }}
          docker tag ${{ github.event.inputs.namespace }}/${{ github.event.inputs.components }}:${{ github.event.inputs.tag }} ${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/${{ github.event.inputs.components }}:${{ github.event.inputs.tag }}
          docker push ${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/${{ github.event.inputs.components }}:${{ github.event.inputs.tag }}
